### ISSUE TITLE
Can't install from pypi

### ISSUE THREAD

**Issue by marksev1** [dhruvbaldawa/commute.py#1]
As the title suggests.

**Comment by dhruvbaldawa** [comment]
What error do you see?

**Comment by marksev1** [comment]
Collecting commute
  Could not find a version that satisfies the requirement commute (from versions: )
No matching distribution found for commute

**Comment by dhruvbaldawa** [comment]
Can you give me output of this command: `pip --version`

**Comment by marksev1** [comment]
pip 9.0.1 (python 2.7)

**Comment by dhruvbaldawa** [comment]
I can reproduce the error on my end, I will get it fixed.
